language: node_js
sudo: false
node_js:
  - 'lts/boron'
  - 'lts/carbon'
  - 'lts/*'
cache:
  directories:
    - 'node_modules'
script:
  - npm install
  - commitlint-travis
  - npm run pre:ci
  - npm run test
