compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - ./yarn-plugins/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.0.0.cjs
