defaultSemverRangePrefix: ""
enableGlobalCache: false
enableTelemetry: true
httpRetry: 10
httpTimeout: 100000

npmRegistryServer: "https://registry.verdaccio.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./yarn-plugins/plugin-postinstall.js   

yarnPath: .yarn/releases/yarn-2.4.1.cjs
