packages:
  - packages/*
  - packages/core/*
  - packages/tools/*
  - packages/ui/*
  - packages/server/*
  - packages/logger/*
  - packages/plugins/audit
  - packages/plugins/auth-memory
  - packages/plugins/htpasswd
  - packages/plugins/ui-theme
  - packages/plugins/memory
  - packages/plugins/local-storage
  - e2e/cli/*
  - e2e/ui
  - website
catalog:
  "@babel/cli": 7.23.9
  "@babel/eslint-parser": 7.23.3
  "@babel/node": 7.23.9
  "@babel/plugin-proposal-class-properties": 7.18.6
  "@babel/plugin-proposal-decorators": 7.23.9
  "@babel/plugin-proposal-export-namespace-from": 7.18.9
  "@babel/plugin-proposal-function-sent": 7.23.3
  "@babel/plugin-proposal-json-strings": 7.18.6
  "@babel/plugin-proposal-nullish-coalescing-operator": 7.18.6
  "@babel/plugin-proposal-numeric-separator": 7.18.6
  "@babel/plugin-proposal-object-rest-spread": 7.20.7
  "@babel/plugin-proposal-optional-chaining": 7.21.0
  "@babel/plugin-proposal-throw-expressions": 7.23.3
  "@babel/plugin-syntax-dynamic-import": 7.8.3
  "@babel/plugin-syntax-import-meta": 7.10.4
  "@babel/plugin-transform-async-to-generator": 7.23.3
  "@babel/plugin-transform-classes": 7.23.8
  "@babel/plugin-transform-runtime": 7.23.9
  "@babel/preset-env": 7.23.9
  "@babel/preset-react": 7.23.3
  "@babel/preset-typescript": 7.23.3
  "@babel/register": 7.23.7
  "@babel/runtime": 7.23.9
  "@changesets/changelog-github": 0.5.0
  "@changesets/cli": 2.27.1
  "@changesets/get-dependents-graph": 1.3.6
  "@crowdin/cli": 3.16.1
  "@crowdin/crowdin-api-client": 1.29.5
  "@dianmora/contributors": 5.0.0
  "@docusaurus/core": 2.4.3
  "@docusaurus/module-type-aliases": 2.4.3
  "@docusaurus/plugin-content-docs": 2.4.3
  "@docusaurus/plugin-google-analytics": 2.4.3
  "@docusaurus/preset-classic": 2.4.3
  "@docusaurus/remark-plugin-npm2yarn": 2.4.3
  "@docusaurus/theme-common": 2.4.3
  "@docusaurus/theme-mermaid": 2.4.3
  "@docusaurus/theme-search-algolia": 2.4.3
  "@docusaurus/types": 2.4.3
  "@docusaurus/utils": 2.4.3
  "@emotion/babel-plugin": 11.10.6
  "@emotion/cache": 11.10.7
  "@emotion/css": 11.10.6
  "@emotion/jest": 11.11.0
  "@fontsource/material-icons": ^4.5.4
  "@fontsource/roboto": ^4.5.8
  "@mdx-js/react": ^1.6.22
  "@mui/icons-material": 5.15.6
  "@mui/material": 5.15.6
  "@mui/styles": 5.15.6
  "@mui/system": 5.15.6
  "@orama/orama": 1.2.4
  "@rematch/core": 2.2.0
  "@rematch/loading": 2.1.2
  "@rematch/persist": 2.1.2
  "@storybook/addon-actions": ^6.5.15
  "@storybook/addon-essentials": ^6.5.15
  "@storybook/addon-interactions": ^6.5.15
  "@storybook/addon-links": ^6.5.15
  "@storybook/builder-webpack5": ^6.5.15
  "@storybook/manager-webpack5": ^6.5.15
  "@storybook/react": ^6.5.15
  "@storybook/testing-library": ^0.2.0
  "@testing-library/dom": 9.3.4
  "@testing-library/user-event": 14.5.2
  "@trivago/prettier-plugin-sort-imports": 4.3.0
  "@tsconfig/docusaurus": ^1.0.2
  "@types/bcryptjs": 2.4.6
  "@types/body-parser": 1.19.5
  "@types/connect": 3.4.38
  "@types/cookiejar": 2.1.5
  "@types/express": 4.17.21
  "@types/express-serve-static-core": 4.17.42
  "@types/hast": ^2.0.0
  "@types/http-errors": 2.0.4
  "@types/jest": 29.5.11
  "@types/jsonwebtoken": 9.0.5
  "@types/lodash": 4.14.202
  "@types/mime": 3.0.4
  "@types/minimatch": 5.1.2
  "@types/node": 20.11.7
  "@types/node-fetch": 2.6.11
  "@types/qs": 6.9.11
  "@types/range-parser": 1.2.7
  "@types/react": 18.2.48
  "@types/react-dom": 18.2.18
  "@types/react-router": ^5.1.20
  "@types/react-router-dom": 5.3.3
  "@types/react-virtualized": 9.21.29
  "@types/redux": 3.6.0
  "@types/semver": 7.5.6
  "@types/send": 0.17.4
  "@types/serve-static": 1.15.5
  "@types/superagent": 4.1.24
  "@types/supertest": 2.0.16
  "@types/testing-library__jest-dom": 6.0.0
  "@types/unist": ^2.0.0
  "@types/validator": 13.11.8
  "@types/webpack": 5.28.5
  "@types/webpack-env": 1.18.4
  "@types/yeoman-environment": 2.10.11
  "@types/yeoman-generator": 5.2.14
  "@types/yeoman-test": 4.0.6
  "@types/yup": 0.32.0
  "@typescript-eslint/eslint-plugin": 6.19.1
  "@typescript-eslint/parser": 6.19.1
  "@verdaccio-scope/verdaccio-auth-foo": 0.0.2
  "@vitest/coverage-v8": 0.34.6
  abortcontroller-polyfill: 1.7.5
  ajv: 8.12.0
  apache-md5: 1.1.8
  aria-query: 5.1.3
  babel-core: 7.0.0-bridge.0
  babel-jest: 29.7.0
  babel-plugin-dynamic-import-node: 2.3.3
  babel-plugin-emotion: 11.0.0
  bcryptjs: 2.4.3
  body-parser: 1.20.2
  chalk: 4.1.2
  classnames: 2.5.1
  clipanion: 3.2.1
  clsx: 1.2.1
  colorette: 2.0.20
  compression: 1.7.4
  concurrently: 8.2.2
  cookies: 0.9.0
  copy-text-to-clipboard: 3.2.0
  core-js: 3.35.0
  cors: 2.8.5
  country-flag-icons: 1.5.9
  cross-env: 7.0.3
  css-loader: 6.9.1
  customprefix-auth: 2.0.0-next.0
  cypress: ^13.6.0
  dayjs: 1.11.10
  debug: 4.3.4
  detect-secrets: 1.0.6
  docusaurus-plugin-sass: ^0.2.1
  docusaurus-plugin-sentry: 1.0.0
  docusaurus-plugin-typedoc: 0.18.0
  dompurify: 3.0.8
  envinfo: 7.11.0
  esbuild: 0.14.10
  esbuild-loader: 2.16.0
  eslint: 8.56.0
  eslint-config-google: 0.14.0
  eslint-config-prettier: 8.10.0
  eslint-plugin-babel: 5.3.1
  eslint-plugin-cypress: 2.15.1
  eslint-plugin-import: 2.29.1
  eslint-plugin-jest: 27.6.3
  eslint-plugin-jsx-a11y: 6.8.0
  eslint-plugin-prettier: 5.1.3
  eslint-plugin-react: 7.33.2
  eslint-plugin-react-hooks: 4.6.0
  eslint-plugin-simple-import-sort: 10.0.0
  eslint-plugin-verdaccio: 10.0.0
  express: 4.19.2
  express-rate-limit: 5.5.1
  fastify: 4.25.2
  fastify-plugin: 4.5.1
  friendly-errors-webpack-plugin: 1.7.0
  fs-extra: 11.2.0
  get-port: 5.1.1
  get-stream: ^6.0.1
  globby: 11.1.0
  got: 11.8.6
  got-cjs: 12.5.4
  gunzip-maybe: ^1.4.2
  handlebars: 4.7.8
  harmony-reflect: 1.6.2
  highlight.js: 11.9.0
  history: 4.10.1
  hpagent: 1.2.0
  html-webpack-plugin: 5.6.0
  http-errors: 2.0.0
  http-status-codes: 2.3.0
  https-proxy-agent: 5.0.1
  husky: 8.0.3
  i18next: 20.6.1
  in-publish: 2.0.1
  jest: 29.7.0
  jest-diff: 29.7.0
  jest-environment-jsdom: 29.7.0
  jest-environment-jsdom-global: 4.0.0
  jest-environment-node: 29.7.0
  jest-junit: 16.0.0
  js-base64: 3.7.6
  js-yaml: 4.1.0
  jsdom: 20.0.3
  JSONStream: 1.3.5
  jsonwebtoken: 9.0.2
  kleur: 4.1.5
  lint-staged: 11.2.6
  localstorage-memory: 1.0.3
  lockfile: 1.0.4
  lodash: 4.17.21
  lowdb: 1.0.0
  lru-cache: 7.18.3
  marked: 11.2.0
  marked-highlight: 2.1.0
  memfs: 3.5.3
  memory-fs: 0.5.0
  merge2: 1.4.1
  mime: 2.6.0
  mini-css-extract-plugin: 2.7.7
  mockdate: 3.0.5
  msw: 0.49.3
  mutationobserver-shim: 0.3.7
  nock: 13.5.1
  node-html-parser: 4.1.5
  node-mocks-http: 1.14.1
  nodemon: 3.0.3
  normalize.css: 8.0.1
  npm-run-all2: 5.0.2
  optimize-css-assets-webpack-plugin: 6.0.1
  ora: 5.4.1
  p-cancelable: 2.1.1
  pino-abstract-transport: 1.1.0
  prettier: 3.2.2
  prism-react-renderer: ^1.2.1
  process-warning: 1.0.0
  raw-loader: 4.0.2
  react-hot-loader: 4.13.1
  react-i18next: 13.5.0
  react-iframe: 1.8.5
  react-json-view: 1.21.3
  react-markdown: 9.0.1
  react-player: 2.14.1
  react-redux: 8.1.3
  react-router: 5.3.4
  react-router-dom: 5.3.4
  react-twitter-widgets: ^1.10.0
  react-virtualized: 9.22.5
  redux: 4.2.1
  redux-persist: 6.0.0
  rimraf: 5.0.5
  sanitize-filename: 1.6.3
  sass: 1.70.0
  sass-loader: ^12.1.0
  selfsigned: 2.4.1
  semver: 7.6.2
  sonic-boom: 3.8.0
  style-loader: 3.3.4
  stylelint: 15.11.0
  stylelint-config-recommended: 10.0.1
  stylelint-config-styled-components: 0.1.1
  stylelint-processor-styled-components: 1.10.0
  stylelint-webpack-plugin: 4.1.1
  supertest: 6.3.4
  tar-stream: ^3.1.7
  terser-webpack-plugin: 5.3.10
  ts-jest: 29.1.0
  ts-node: 10.9.2
  typedoc: 0.23.25
  typedoc-github-wiki-theme: ^1.0.1
  typedoc-plugin-markdown: 3.14.0
  typedoc-plugin-merge-modules: 4.0.1
  typedoc-plugin-missing-exports: 1.0.0
  undici-types: 5.28.2
  unix-crypt-td-js: 1.1.4
  update-ts-references: 3.2.1
  url-loader: 4.1.1
  use-is-in-viewport: ^1.0.9
  usehooks-ts: 2.9.5
  validator: 13.11.0
  verdaccio: 7.0.0-next-7.18
  vitest: 1.6.0
  webpack: 5.90.0
  webpack-bundle-analyzer: 4.10.1
  webpack-bundle-size-analyzer: 3.1.0
  webpack-dev-server: 3.11.3
  webpack-manifest-plugin: 4.1.1
  webpack-merge: 5.10.0
  whatwg-fetch: 3.6.20
  yaml: 2.4.3
  yarn: 1.22.22
  yeoman-assert: 3.1.1
  yeoman-environment: 3.19.3
  yeoman-generator: 5.9.0
  yeoman-test: 6.3.0
  yosay: 2.0.2
  yup: 0.32.11
