packages:
  - packages/*
  - packages/core/*
  - packages/tools/*
  - packages/experimental/*
  - packages/plugins/audit
  - packages/plugins/auth-memory
  - packages/plugins/htpasswd
  - packages/plugins/ui-theme
  - packages/plugins/memory
  - packages/plugins/local-storage
  - website
  - test/e2e-*
  - test/helpers
