web:
  enable: true
  title: verdaccio-server-e2e
  login: true

log: { type: stdout, format: json, level: warn }

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

auth:
  htpasswd:
    file: ./htpasswd

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

_debug: true
