name: CI Website

on:
  # disabled on master until deployment is need it
  # push:
  #   branches:
  #     - master
  pull_request:
    paths:
      - .github/workflows/ci-website.yml
      - 'website/**'
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [14]

    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
      - name: Install
        run: pnpm recursive install
      - name: Format
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Build website
        run: |
          cd website
          pnpm build
