name: format

on: [pull_request]
jobs:
  format:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [16]

    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: npm i pnpm@latest -g
      - name: Install
        run: pnpm recursive install
      - name: Format
        run: pnpm format:check
