name: CI Lint

on: [push, pull_request]

jobs:
  ci-lint:
    name: Node Lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Use Node 
      uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: yarn install --immutable
    - name: Format
      run: yarn format:check
    - name: Lint
      run: yarn lint
    - name: Lint Lockfile
      run: yarn lint:lockfile
