storage: ./mock-store

web:
  enable: false
  title: verdaccio-server-unit-test

auth:
  auth-memory:
    users:
      test:
        name: test
        password: test

log: { type: stdout, format: pretty, level: warn }

packages:
  '@*/*':
    access: $all
    publish: none
    unpublish: none
  '**':
    access: $all
    publish: none
    unpublish: none

_debug: true
