name: 'Cache build'
description: 'get or set cache build'

runs:
  using: composite
  steps:
    - name: Cache .pnpm-store
      id: cache-npm
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.event.pull_request.number }}-${{ runner.os }}
        restore-keys: |
          pnpm-

