version: '3.1'

services:
  nginx:
    build:
      context: ''
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
    networks:
      - node-network
    container_name: 'nginx'
    depends_on:
      - verdaccio
      - verdaccio3
      - verdaccio-root
  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: 'verdaccio_relative_path_v4'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf/v4:/verdaccio/conf'
  verdaccio-root:
    image: verdaccio/verdaccio:4
    container_name: 'verdaccio_relative_path_v4_root'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=8000
    ports:
      - '8000:8000'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf/v4_root:/verdaccio/conf'
  verdaccio3:
    image: verdaccio/verdaccio:3
    container_name: 'verdaccio_relative_path_latest_v3'
    networks:
      - node-network
    ports:
      - '7771:7771'
    environment:
      - PORT=7771
    volumes:
      - './storage:/verdaccio/storage'
      - './conf/v3:/verdaccio/conf'

networks:
  node-network:
    driver: bridge
