npmRegistryServer: ${registry}
yarnPath: .yarn/releases/yarn.js
# on CI modify the lock file is not allowed
# https://github.com/yarnpkg/berry/discussions/3486#discussioncomment-1379344
enableImmutableInstalls: false
unsafeHttpWhitelist:
  - localhost
