name: Test local registry for js vulnerabilities

on:
  schedule:
  - cron: '0 4 * * 4'
jobs:
  security:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test for public javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@1.15.10
        with:
          scan-url: "https://registry.verdaccio.org"
