
name: Changesets

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 5.x
  pull_request:
    branches:
      - 5.

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/5.x' && github.repository == 'verdaccio/verdaccio'
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: install pnpm
        run: npm install pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: create versions
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
