name: E2E CLI

on: [pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [14]

    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}
      - run: sudo npm install -g pnpm
      - name: Install
        run: pnpm install --lockfile-only
      - name: Build
        run: pnpm run code:build
      - name: Test CLI
        run: pnpm run test:e2e:cli
        env:
          NODE_ENV: production
