name: E2E CLI

on: [pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [14]

    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn code:build
      - name: Test CLI
        run: yarn test:e2e:cli
