name: E2E CLI

on:
  push:
    branches:
      - 5.x
      - 'changeset-release/6.x'
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - 'packages/**'
      - 'jest/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'test/**'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [14]

    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: npm i -g pnpm@latest
      - name: Install
        run: pnpm recursive install
      - name: Clean
        run: pnpm clean
      - name: Build
        run: pnpm build
      - name: Test CLI
        run: pnpm test:e2e:cli
        env:
          DEBUG: verdaccio:e2e*
