name: CI with pnpm 6

on:
  push:
    branches:
      - 5.x
      - 'changeset-release/6.x'
  pull_request:
    paths:
      - .changeset/**
      - .github/workflows/ci.yml
      - 'packages/**'
      - 'jest/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 15]

    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: sudo npm i pnpm@dev -g
      - name: Install
        run: pnpm recursive install
      - name: Format
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Clean
        run: pnpm clean
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
        env:
          DEBUG: verdaccio:web:*
