name: CI windows

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * SUN' 
permissions:
  contents: read
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:nightly-master
        ports:
          - 4873:4873
        env:
          NODE_ENV: production          
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # tag=v3
    - name: Node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
      with:
        node-version-file: '.nvmrc'
    - name: Install pnpm
      run: npm i pnpm@6.32.15 -g
    - name: set store
      run: |
        mkdir ~/.pnpm-store
        pnpm config set store-dir ~/.pnpm-store
    - name: Install
      run: pnpm recursive install --frozen-lockfile --registry http://localhost:4873
    - name: Cache .pnpm-store
      uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-
  lint:
    runs-on: windows-latest
    name: Lint
    needs: prepare
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # tag=v3
      - name: Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: npm i pnpm@6.32.15 -g
      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install
        run: pnpm recursive install --offline --frozen-lockfile --reporter=silence --ignore-scripts
      - name: Lint
        run: pnpm lint
  format:
    runs-on: windows-latest
    name: Format
    needs: prepare
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # tag=v3
      - name: Use Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: npm i pnpm@6.32.15 -g
      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install
        run: pnpm recursive install --offline --frozen-lockfile --reporter=silence --ignore-scripts
      - name: Lint
        run: pnpm format:check
  build:
    needs: [format, lint]
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        node_version: [18]
    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # tag=v3
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: npm i pnpm@6.32.15 -g
      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install
        run: pnpm recursive install --offline --frozen-lockfile --reporter=silence --ignore-scripts --registry http://localhost:4873
      - name: build
        run: pnpm build
      - name: Test
        run: pnpm test
  ci-e2e-ui:
    needs: [format, lint]
    runs-on: windows-latest
    name: UI Test E2E
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # tag=v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: npm i pnpm@6.32.15 -g
      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install
        run: pnpm recursive install --offline --frozen-lockfile --reporter=silence --registry http://localhost:4873
      - name: build
        run: pnpm build
      - name: Test UI
        run: pnpm test:e2e:ui
        # env:
        #  DEBUG: verdaccio:e2e*
