name: CI Website

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/ci-website.yml
      - "website/**"
jobs:
  ci:
    name: Node ${{ matrix.node_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [14]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install
        run: pnpm recursive install
      - name: Lint website
        run: pnpm lint
      - name: Build website
        run: |
          cd website
          pnpm build
