name: CI Website

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/ci-website.yml
      - 'website/**'
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [14]

    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install
        run: pnpm recursive install
      - name: Format
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Build website
        run: |
          cd website
          pnpm build
