name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Node ${{ matrix.node_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [16, 18, 20]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install
      run: yarn install --immutable
    - name: Format
      run: yarn format:check
    - name: Lint
      run: yarn lint        
    - name: Build
      run: yarn build
    - name: Types
      run: yarn code:types            
    - name: Test
      run: yarn test
