name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Node ${{ matrix.node_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [10, 12, 13, 14]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node_version: ${{ matrix.node_version }}
    - name: Install
      run: yarn
    - name: Bootstrap Lerna
      run: yarn bootstrap
    - name: Lint
      run: yarn lint
    - name: Clean
      run: yarn clean
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
