name: CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - 'packages/**'
      - 'jest/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'

jobs:
  ci:
    name: Node ${{ matrix.node_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [10, 12, 14]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node_version: ${{ matrix.node_version }}
    - name: Install pnpm
      run: npm i -g pnpm
    - name: Install
      run: pnpm recursive install
    - name: Install packages
      run: pnpm install -r
    - name: Lint
      run: pnpm lint
    - name: Clean
      run: pnpm clean
    - name: Build
      run: pnpm build
    - name: Test
      run: pnpm test
