name: CI

on: [push, pull_request]

permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}-5.x
  cancel-in-progress: true  

jobs:
  build: 
    strategy:
      fail-fast: false
      matrix:
        node_version: [14, 16, 18, 19, 20, 21, 22]  
    uses: verdaccio/verdaccio/.github/workflows/yarn-ci.yml@master
    with:
      node_version: ${{ matrix.node_version }}
