name: CI

on:
  push:
    branches:
      - master
      - 'changeset-release/master'
  pull_request:
    paths:
      - .changeset/**
      - .github/workflows/ci.yml
      - 'packages/**'
      - 'jest/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14 
    - name: Install pnpm
      run: npm i pnpm@latest -g
    - name: set store
      run: | 
        mkdir ~/.pnpm-store
        pnpm config set store-dir ~/.pnpm-store
    - name: Install
      run: pnpm recursive install --frozen-lockfile --registry http://localhost:4873
    - uses: actions/upload-artifact@v2
      with:
        name: pnpm-store
        path: ~/.pnpm-store
  ci:
    runs-on: ubuntu-latest
    name: ubuntu-latest / Node 14
    needs: prepare
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install pnpm
        run: npm i pnpm@latest -g
      # - name: Install
      #   run: pnpm recursive install --frozen-lockfile --registry http://localhost:4873
      # - name: Lint
      #   run: pnpm lint
      # - name: Clean
      #   run: pnpm clean
      # - name: Build
      #   run: pnpm build
      # - name: Test
      #   run: pnpm test
