name: CI

on: [push, pull_request]

permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}-7.x
  cancel-in-progress: true  

jobs:
  build: 
    strategy:
      fail-fast: false
      matrix:
        node_version: [20, 22]    
    uses: verdaccio/verdaccio/.github/workflows/yarn-ci.yml@master
    with:
      node_version: ${{ matrix.node_version }}
