name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Node ${{ matrix.node_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [12, 14, 15]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node_version }}
    - run: sudo npm install -g pnpm
    - name: Install
      run: pnpm install --lockfile-only
    - name: Build
      run: pnpm run code:build
    - name: Lint
      run: pnpm run lint
    - name: Test
      run: pnpm run test
