---
name: contributors

on:
  workflow_dispatch:
  schedule:
    # twice peer week
    - cron: '0 0 * * 1,4'
  # for now, scheduled, we can enable on push master but not make much sense now
  # push:
  #   branches:
  #     - master
jobs:
  prepare:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - name: install pnpm
        run: sudo npm i pnpm@6.24.1 -g
      - name: set store
        run: | 
          mkdir ~/.pnpm-store
          pnpm config set store-dir ~/.pnpm-store
      - name: setup pnpm config registry
        run: pnpm config set registry https://registry.verdaccio.org
      - name: install dependencies
        run: pnpm install
      - name: update contributors
        run: pnpm run contributors
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: format
        run: pnpm format
      - name: Commit & Push changes
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.TOKEN_VERDACCIOBOT_GITHUB }}
          message: "chore: updated contributors list"
          branch: master
          author_email: verdaccio.npm@gmail.com
          author_name: verdacciobot
