name: Docker & Publish Pre-check

on: [push, pull_request]

jobs:
  testDocker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: yarn docker
      env:
        VERDACCIO_BUILD_REGISTRY: https://registry.verdaccio.org
