name: Docker publish to docker.io

on:
  push:
    paths:
      - .github/workflows/docker-publish.yml
      - 'src/**'
      - 'conf/**'
      - 'types/**'
      - 'docker-bin/**'
      - 'bin/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarn/**'
      - '.yarnrc.yaml'
      - '.pnp.js'
    branches:
      - '**'
    tags:
     - 'v*'

jobs:
  docker-publish:
      secrets: inherit
      uses: verdaccio/verdaccio/.github/workflows/shared-docker-publish.yml@master    
      with:
        tag-latest: false
        tag-custom: 5.x-next
        tag-custom-only: ${{ github.ref == 'refs/heads/5.x' }}
