name: Docker publish to GitHub registry

on:
  push:
    paths:
      - .github/workflows/docker-publish.yml
      - 'packages/**'
      - 'docker-bin/**'
      - 'package.json'
      - 'lerna.json'

jobs:
  testDocker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/verdaccio/verdaccio/verdaccio
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.GITHUB_REGISTRY_TOKEN}}
        registry: docker.pkg.github.com
        tags: "5.x"

