name: E2E Docker Proxy Apache Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    # run every sunday
    - cron: '0 0 * * 0'
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v3
      
    - name: Start containers
      run: docker-compose -f "./e2e/docker/apache-verdaccio/docker-compose.yaml" up -d --build

    - name: Install node
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
      with:
        node-version: 18
    - name: verdaccio cli
      run: npm install -g verdaccio --registry http://localhost
    - name: gastby cli 
      run:  npm install -g gatsby-cli --registry http://localhost
    - name: netlify cli 
      run:  npm install -g netlify-cli --registry http://localhost
    - name: angular cli 
      run:  npm install -g @angular/cli --registry http://localhost

    - name: Stop containers
      if: always()
      run: docker-compose -f "./e2e/docker/apache-verdaccio/docker-compose.yaml" down
