name: Docker publish to docker.io

on:
  push:
    paths:
      - .github/workflows/docker-publish.yml
      - .github/workflows/docker-publish.yml
      - 'packages/**'
      - 'docker-bin/**'
      - 'package.json'
      - 'pnpm-*.yaml'
      - 'Dockerfile'
      - '.dockerignore'
    branches:
      - 'master'
    tags:
      - 'v*'

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # tag=v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - uses: docker/login-action@v1
        name: Login Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare docker image tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}
          tag-custom: nightly-master
          tag-custom-only: ${{ github.ref == 'refs/heads/master' }}
          tag-semver: |
            {{version}}
            {{major}}
            {{major}}.{{minor}}
      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
