name: E2E Docker Proxy Nginx Test

concurrency:
  group: docker-nginx-${{ github.ref }}
  cancel-in-progress: true  


on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3
      
    - name: Start containers
      run: docker compose -f "./e2e/docker/proxy-nginx/docker-compose.yaml" up -d --build

    - name: Install node
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
      with:
        node-version-file: '.nvmrc'
    - name: npm setup
      run: |
        npm config set fetch-retries="10"
        npm config set fetch-retry-factor="50"
        npm config set fetch-retry-mintimeout="20000"
        npm config set fetch-retry-maxtimeout="80000"      
    - name: verdaccio cli
      run: npm install -g verdaccio --registry http://localhost
    - name: gastby cli 
      run:  npm install -g gatsby-cli --registry http://localhost
    #- name: netlify cli 
    #  run:  npm install -g netlify-cli --registry http://localhost
    - name: angular cli 
      run:  npm install -g @angular/cli --registry http://localhost

    - name: Stop containers
      if: always()
      run: docker compose -f "./e2e/docker/proxy-nginx/docker-compose.yaml" down
