name: E2E UI

on: [pull_request]

permissions:
  contents: read
concurrency:
  group: e2e-ui-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: UI Test E2E
    services:
      verdaccio:
        image: verdaccio/verdaccio:6
        ports:
          - 4873:4873
        env:
          NODE_ENV: production
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build application with Node ${{ matrix.node_version }}
        uses: ./.github/actions/build-app
        with:
          node-version: ${{ matrix.node_version }}
      - name: Test UI
        run: pnpm test:e2e:ui
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: videos
          path: /home/runner/work/verdaccio/verdaccio/e2e/ui/cypress/videos
