name: E2E UI

on: [pull_request]
permissions:
  contents: read
concurrency:
  group: e2e-ui-${{ github.ref }}
  cancel-in-progress: true  
jobs:
  test:
    runs-on: ubuntu-latest
    name: UI Test E2E
    services:
      verdaccio:
        image: verdaccio/verdaccio:6
        ports:
          - 4873:4873
        env:
          NODE_ENV: production
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare
      - name: Install
        run: pnpm install --reporter=silence --registry http://localhost:4873
      - name: build
        run: pnpm build
      - name: Test UI
        run: pnpm test:e2e:ui
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: videos
          path: /home/runner/work/verdaccio/verdaccio/e2e/ui/cypress/videos
