name: E2E UI

on: [pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    name: UI Test E2E
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
        env:
          NODE_ENV: production
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag=v3
      - name: Use Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # tag=v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: |
         corepack enable
         corepack prepare --activate pnpm@6.32.15
      - name: Install
        run: pnpm install --frozen-lockfile --reporter=silence --registry http://localhost:4873
      - name: build
        run: pnpm build
      - name: Test UI
        run: pnpm test:e2e:ui
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: videos
          path: /home/runner/work/verdaccio/verdaccio/e2e/ui/cypress/videos
