on:
  schedule:
    - cron: '0 */4 * * *'
    push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/e2e-jest-workflow.yml
      - scripts/e2e-setup-ci.sh

name: 'E2E Jest with Verdaccio'
jobs:
  chore:
    name: 'Validating Jest'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: 'Use Node.js 10.x'
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: yarn install --pure-lockfile
      - name: 'Run verdaccio in the background'
        run: |
          nohup node ./scripts/run-verdaccio.js &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          yarn init --yes
          yarn add jest --registry http://localhost:4873

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad --registry http://localhost:4873 --verbose
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
