on:
  schedule:
  - cron: '0 3 * * 5'
  pull_request:
    branches:
    - '**'

name: 'E2E Angular CLI with verdaccio'
jobs:
  npm:
    name: 'npm6:angular example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: 'Use Node.js 16.x'
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16.x
      - name: 'install latest npm'
        run: npm i -g npm@latest-6
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js --config ./scripts/e2e-config.yaml &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          echo "registry=http://localhost:4873" > ~/.npmrc
          npm config set loglevel="http"
          npm config set fetch-retries="5"
          npm config set fetch-retry-factor="50"
          npm config set fetch-retry-mintimeout="20000"
          npm config set fetch-retry-maxtimeout="80000"
          npm install -g @angular/cli
          ng new verdaccio-angular --interactive=false

          cd verdaccio-angular
          npm install @angular-devkit/core@next @babel/preset-env @babel/core -D

          npm run ng build --aot
  npm7:
    name: 'npm7:angular example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: 'Use Node.js 16.x'
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16.x
      - name: 'install latest npm'
        run: npm i -g npm@next-7
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js --config ./scripts/e2e-config.yaml &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          echo "registry=http://localhost:4873" > ~/.npmrc
          npm config set loglevel="silent"
          npm config set fetch-retries="5"
          npm config set fetch-retry-factor="50"
          npm config set fetch-retry-mintimeout="20000"
          npm config set fetch-retry-maxtimeout="80000"
          npm install -g @angular/cli
          ng new verdaccio-angular --interactive=false

          cd verdaccio-angular
          npm install @angular-devkit/core@next @babel/preset-env @babel/core -D

          npm run ng build --aot
  npm8:
    name: 'npm8:angular example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: 'Use Node.js 16.x'
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16.x
      - name: 'install latest npm'
        run: npm i -g npm@next-8
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js --config ./scripts/e2e-config.yaml &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          echo "registry=http://localhost:4873" > ~/.npmrc
          npm config set loglevel="silent"
          npm config set fetch-retries="5"
          npm config set fetch-retry-factor="50"
          npm config set fetch-retry-mintimeout="20000"
          npm config set fetch-retry-maxtimeout="80000"
          npm install -g @angular/cli
          ng new verdaccio-angular --interactive=false

          cd verdaccio-angular
          npm install @angular-devkit/core@next @babel/preset-env @babel/core -D

          npm run ng build --aot
  npm9:
    name: 'npm9:angular example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: 'Use Node.js 18.x'
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js --config ./scripts/e2e-config.yaml &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          echo "registry=http://localhost:4873" > ~/.npmrc
          npm config set loglevel="silent"
          npm config set fetch-retries="5"
          npm config set fetch-retry-factor="50"
          npm config set fetch-retry-mintimeout="20000"
          npm config set fetch-retry-maxtimeout="80000"
          npm install -g @angular/cli
          ng new verdaccio-angular --interactive=false

          cd verdaccio-angular
          npm install @angular-devkit/core@next @babel/preset-env @babel/core -D

          npm run ng build --aot
