on:
  pull_request:
    branches:
    - '**'

name: 'E2E Next CLI with verdaccio'
jobs:
  npm10:
    name: 'npm10:angular example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: 'Use Node.js'
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest npm 10'
        run: npm i -g npm@next-10         
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js --config ./scripts/e2e-config.yaml &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          echo "registry=http://localhost:4873" > ~/.npmrc
          npm config set loglevel="info"
          npm config set fetch-retries="5"
          npm config set fetch-retry-factor="50"
          npm config set fetch-retry-mintimeout="20000"
          npm config set fetch-retry-maxtimeout="80000"
          npm install next@latest react@latest react-dom@latest --registry http://localhost:4873  --loglevel info
          npm run build          
