name: E2E Generator Verdaccio Plugin

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'

concurrency:
  group: generator-plugin-${{ github.ref }}
  cancel-in-progress: true  

jobs:
  e2e-plugin-generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18,20, 21]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: |
          corepack enable
          corepack install
      - uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
      - name: install verdaccio
        run: npm install -g verdaccio@5
      - name: Start server
        run: verdaccio -c e2e/docker/generator-e2e/generator.yaml &
      - name: ping server
        run: curl http://localhost:4873/-/ping
      - name: login
        run: npx npm-cli-login -u test -p test -e test@domain.test -r http://localhost:4873
      - name: publish
        run: pnpm local:publish
      - name: install yeoman
        run: npm install -g yo@4 --loglevel=info
      - name: install generator
        run: npm install -g generator-verdaccio-plugin --loglevel=info --registry http://localhost:4873
# Future: add a test to verify the plugin is working with prompt 
