name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node (latest)
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14
    - run: sudo npm install -g pnpm
    - name: Install
      run: pnpm install
    - name: Build
      run: pnpm run code:build
    - name: Publish
      run: sh scripts/publish.sh
      env:
        REGISTRY_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
        REGISTRY_URL: registry.npmjs.org
    - name: Create release notes
      run: sh scripts/github-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
