name: Release Canary

on:
  workflow_dispatch:
  push:
    # branches:
    #   - 7.x
jobs:
  release:
    secrets: inherit
    uses: verdaccio/verdaccio/.github/workflows/x-release-snapshot.yml@ci-refactor
