name: Module Smoke Test Node.js 12
on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2    
      - name: Use Node (latest)
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # tag=v2.5.1
        with:
          node-version: 12
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:5
      - name: login    
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873                 
      - name: Build
        run: yarn build
      - name: Types
        run: yarn code:types           
      - name: Bump up package
        run: npm version prerelease --no-git-tag-version --preid $(date +%s%N)          
      - name: publish verdaccio 
        run:  npm publish --registry http://localhost:4873
      - name: install verdaccio 
        run:  npm i -g verdaccio --loglevel info --registry http://localhost:4873
      - name: verdaccio version 
        run:  verdaccio --version
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --force
          npm install jest@27.5.1 --registry http://localhost:4873
          npm install verdaccio --registry http://localhost:4873
          echo "test('require module should works', () => { const {runServer} = require('verdaccio') });" | tee module.spec.js
          cat module.spec.js
          yarn jest    
