name: Docker Smoke Test 5.x
on:
  workflow_dispatch:
  push:
    # branches:
    #   - 5.x
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 18
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:5.x-next
      - name: publish verdaccio 
        run:  npm publish --registry http://localhost:4873
