name: Module Smoke Test 5.x
on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3    
      - name: Use Node (latest)
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version-file: '.nvmrc'
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:5
      - name: login    
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873                 
      - name: Build
        run: yarn build
      - name: Types
        run: yarn code:types           
      - name: Bump up package
        run: npm version prerelease --no-git-tag-version --preid $(date +%s%N)          
      - name: publish verdaccio 
        run:  npm publish --registry http://localhost:4873
      - name: install verdaccio 
        run:  npm i -g verdaccio --loglevel info --registry http://localhost:4873
      - name: verdaccio version 
        run:  verdaccio --version
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --force
          npm install jest --registry http://localhost:4873
          npm install verdaccio --registry http://localhost:4873
          echo "test('require module should works', () => { const {runServer} = require('verdaccio') });" | tee module.spec.js
          cat module.spec.js
          yarn jest    
