name: Docker Smoke Test
on:
  workflow_dispatch:
  push:
permissions:
  contents: read

concurrency:
  group: e2e-docker-pkgs-${{ github.ref }}-5.x
  cancel-in-progress: true  

jobs:
  smoke:  
    uses: verdaccio/verdaccio/.github/workflows/x-smok-test-docker.yml@master
    with:
      docker_tag: '5.x-next'

