---
name: static data

on:
  workflow_dispatch:
  schedule:
    # twice peer week
    - cron: '0 0 * * 1,4'
  # for now, scheduled, we can enable on push master but not make much sense now
  # push:
  #   branches:
  #     - master
jobs:
  prepare:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version: 18.x
      - name: install pnpm
        run: sudo npm i pnpm@latest-6 -g
      - name: set store
        run: | 
          mkdir ~/.pnpm-store
          pnpm config set store-dir ~/.pnpm-store
      - name: setup pnpm config registry
        run: pnpm config set registry https://registry.verdaccio.org
      - name: install dependencies
        run: pnpm install
      - name: Build Translations percentage
        run: pnpm build --filter "@verdaccio/crowdin-translations"
      - name: update contributors
        run: pnpm run contributors
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update translations
        run: pnpm run translations
        env:
          TOKEN: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}          
      - name: format
        run: pnpm format
      - name: Commit & Push changes
        uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba # tag=v1.3
        with:
          github_token: ${{ secrets.TOKEN_VERDACCIOBOT_GITHUB }}
          message: "chore: updated static data"
          branch: master
          author_email: verdaccio.npm@gmail.com
          author_name: verdacciobot
