on:
  workflow_call:

jobs:
  testDocker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Build
      run: docker build .
      env:
        VERDACCIO_BUILD_REGISTRY: https://registry.npmjs.org
