name: translations progress

on:
  # or manual triggered
  workflow_dispatch:
  schedule:
    # twice a week
    - cron: '0 0 * * 1,4'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: install pnpm
        run: sudo npm i pnpm@latest-6 -g
      - name: Install dependencies
        run: pnpm install
      - name: update translations
        run: pnpm run website:translations
        env:
          TOKEN: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
      - name: Commit & Push changes
        uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba # tag=v1.3
        with:
          github_token: ${{ secrets.TOKEN_VERDACCIOBOT_GITHUB }}
          message: "chore: updated contributors list"
          branch: master
          author_email: verdaccio.npm@gmail.com
          author_name: verdacciobot
