on:
  workflow_call:
  
jobs:
  npm10:
    name: 'npm10:audit example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest npm 10'
        run: npm i -g npm@next-10  
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js  --config ./scripts/e2e-config.yaml  &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --yes
          npm install next --registry http://localhost:4873  --loglevel info
          npm audit
