on:
  workflow_call:
  
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Use Node (latest)
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Types
      run: yarn code:types      
    - name: Publish
      run: sh scripts/publish.sh
      env:
        REGISTRY_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
        REGISTRY_URL: registry.npmjs.org
    - name: Create release notes
      run: sh scripts/github-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
