on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
        description: 'Docker tag to use for the verdaccio image'
        default: '5'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 20
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:${{ inputs.docker_tag }}
      - name: verdaccio cli 
        run:  npm install -g verdaccio --registry http://localhost:4873                        
      - name: gastby cli 
        run:  npm install -g gatsby-cli --registry http://localhost:4873
      - name: netlify cli 
        run:  npm install -g netlify-cli --registry http://localhost:4873
      - name: angular cli 
        run:  npm install -g @angular/cli --registry http://localhost:4873
