on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
        description: 'Docker tag to use for the verdaccio image'
        default: '5'
      module_tag:
        required: true
        type: string
        description: 'Npmjs module tag to use for the verdaccio image'
        default: '@latest'   
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:${{ inputs.docker_tag }}
      - name: verdaccio cli 
        run:  npm install -g verdaccio${{inputs.module_tag }} --registry http://localhost:4873                        
      - name: gastby cli 
        run:  npm install -g gatsby-cli --registry http://localhost:4873
      - name: netlify cli 
        run:  npm install -g netlify-cli --registry http://localhost:4873
      - name: angular cli 
        run:  npm install -g @angular/cli --registry http://localhost:4873
