on:
  workflow_call:

jobs:
  ci-lint:
    name: Node Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use Node 
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: yarn install --immutable
    - name: Format
      run: yarn format:check
    - name: Lint
      run: yarn lint
    - name: Lint Lockfile
      run: yarn lint:lockfile
