on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
jobs:
  ci:
    name: Node ${{ inputs.node_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Use Node ${{ inputs.node_version }}
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install
      run: yarn install --immutable
    - name: Build
      run: yarn build
    - name: Types
      run: yarn code:types            
    - name: Test
      run: yarn test
