on:
  workflow_call:

jobs:
  ci-lint:
    name: Node Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Use Node 
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: yarn install --immutable
    - name: Format
      run: yarn format:check
    - name: Lint
      run: yarn lint
    - name: Lint Lockfile
      run: yarn lint:lockfile
