on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
jobs:
  ci:
    name: Node ${{ inputs.node_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use Node ${{ inputs.node_version }}
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install
      run: yarn install --immutable
    - name: Build
      run: yarn build
    - name: Types
      run: yarn code:types            
    - name: Test
      run: yarn test
